#theme: jekyll-theme-architect
theme: minima
title: Atomic Architects
description: The Atomic Architects is a research group at MIT working at the intersection of physics, geometry, and machine learning to design algorithms that aid in the understanding and design of physical systems.
markdown: kramdown
