theme: jekyll-theme-architect
title: Atomic Architects
description: The Atomic Architects Research Group designs algorithms to understand and generate atomic structures (molecules, crystals, nanoclusters, proteins, etc) for applications in materials science, chemistry, and biology. 
