theme: jekyll-theme-architect
title: Atomic Architects
description: The Atomic Architects Research Group designs algorithms to understand and generate atomic structures for applications in materials science, chemistry, and biology. <br> <a href="./index.html">home</a> | <a href="./research.html">research</a> |  <a href="./people.html">people</a>
