theme: jekyll-theme-architect
title: Atomic Architects
description: <a href="./index.html" style="color:white">home</a> | <a href="./research.html">research</a> |  <a href="./people.html">people</a> <br> The Atomic Architects Research Group designs algorithms to understand and generate atomic structures for applications in materials science, chemistry, and biology. 
